version: '3.5'

services:

  backend:
    build: 
      context: ./backend
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - ./backend:/go/src/github.com/skygate/skylabs-js/backend

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
